media: ""
content:
  - name: pages
    label: Pages
    type: collection
    path: C:\00 Projects\000 JFCarpio.com Website
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text   