"""Bilingual commercial details for the focused report offer."""
import html
def report_body(lang,old_body):
 en=lang=='en'
 title='One question. A clearer business decision.' if en else 'Una pregunta. Una decisión empresarial más clara.'
 intro='For your shop, small business or medical office. You need evidence for <strong>the decision in front of you</strong>. Get a focused written business report for <strong>USD 100</strong>, delivered within <strong>72 hours</strong> after your interview and complete inputs.' if en else 'Para tu tienda, pequeño negocio o consultorio. Necesitas evidencia para <strong>la decisión que tienes delante</strong>. Recibe un reporte empresarial enfocado por <strong>USD 100</strong>, entregado en hasta <strong>72 horas</strong> después de la entrevista y de recibir la información completa.'
 steps=[('Send your question','Tell us what you need to decide, your business context and deadline. We confirm that the scope fits a focused report before you commit.'),('Complete a short questionnaire','We send the questions needed to understand the situation. Include relevant figures or documents; do not send unnecessary personal or customer data.'),('Have a 10-minute online interview','We clarify the question, assumptions and available evidence. English and Spanish are available.'),('Receive your report within 72 hours','You receive findings, important uncertainties, options and practical next steps in writing. The delivery clock begins after the interview and receipt of the complete agreed inputs.')] if en else [('Envía tu pregunta','Cuéntanos qué necesitas decidir, el contexto de tu negocio y tu plazo. Confirmamos que el alcance cabe en un reporte enfocado antes de que te comprometas.'),('Completa un cuestionario breve','Te enviamos las preguntas necesarias para entender el caso. Incluye cifras o documentos relevantes; evita datos personales o de clientes que no sean necesarios.'),('Conversa con nosotros durante 10 minutos','En una entrevista online aclaramos la pregunta, los supuestos y la evidencia disponible. Podemos trabajar en inglés o español.'),('Recibe tu reporte en hasta 72 horas','Recibes por escrito los hallazgos, las incertidumbres relevantes, las opciones y los próximos pasos. El plazo empieza después de la entrevista y de recibir toda la información acordada.')]
 example='Is this price sustainable? Which customer group should I focus on? What explains a margin decline? Which indicators would reveal the problem earlier?' if en else '¿Este precio es sostenible? ¿En qué clientes conviene concentrarme? ¿Qué explica la caída del margen? ¿Qué indicadores permitirían detectar antes el problema?'
 scope='One well-defined question, not an open-ended strategy engagement. If the case needs a larger study, we explain the scope before accepting it. The report supports your decision; it does not promise revenue, investment returns or a guaranteed outcome.' if en else 'Una pregunta bien delimitada, no una consultoría de alcance indefinido. Si el caso requiere un estudio mayor, te lo explicamos antes de aceptarlo. El reporte aporta criterio para decidir; no promete ingresos, retornos de inversión ni un resultado garantizado.'
 subject='Focused business report — USD 100' if en else 'Reporte empresarial enfocado — USD 100'
 email='mailto:jfcarpio@gmail.com?subject='+__import__('urllib.parse',fromlist=['quote']).quote(subject)
 out=[f'<p class="kick">{"Focused business reports" if en else "Reportes empresariales enfocados"}</p>',f'<h1>{title}</h1>',f'<p class="section-intro">{intro}</p>',f'<div class="offer-line"><strong>USD 100</strong><span>{"One agreed question · online · up to 72 hours" if en else "Una pregunta acordada · online · hasta 72 horas"}</span></div>',f'<p class="cta"><a class="btn p" href="{email}">{"Send your question by email" if en else "Envía tu pregunta por email"}</a><a class="btn" href="{"/en/contact/" if en else "/contacto/"}">{"Other contact options" if en else "Otras formas de contacto"}</a></p>',f'<section class="accent-blue"><h2>{"How it works" if en else "Cómo funciona"}</h2><ol class="steps">'+''.join(f'<li><strong>{html.escape(h)}</strong><p>{html.escape(p)}</p></li>' for h,p in steps)+'</ol></section>',f'<section class="accent-orange"><h2>{"Bring a question that matters" if en else "Trae una pregunta que importe"}</h2><p>{example}</p></section>',f'<div class="report-scope"><h2>{"What is included" if en else "Qué incluye"}</h2><p>{"A written analysis of the agreed question, evidence and assumptions, key tradeoffs and actionable next steps." if en else "Un análisis escrito de la pregunta acordada, evidencia y supuestos, los dilemas relevantes y los próximos pasos."}</p><p>{scope}</p></div>']
 return out
def report_schema(lang,canon):
 return {'@type':'Service','@id':canon+'#service','name':'Focused business report' if lang=='en' else 'Reporte empresarial enfocado','serviceType':'Focused business research and consulting','provider':{'@id':'https://jfcarpio.com/#organization'},'areaServed':'Worldwide','availableLanguage':['English','Spanish'],'offers':{'@type':'Offer','price':'100','priceCurrency':'USD','url':canon,'description':'One agreed business question; questionnaire; 10-minute online interview; written report within 72 hours after interview and complete inputs.'}}
